# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "bento/ubuntu-16.04"
CPUS = "2"
HOST_NAME = "puppet-test"
MEMORY = "4000"
PRIVATE_IP = "192.168.7.8"

Vagrant.configure("2") do |config|
  config.vm.box= "#{BOX}"

  config.vm.provider :virtualbox do |vb|
   vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
   vb.customize ["modifyvm", :id, "--memory", MEMORY]
   vb.customize ["modifyvm", :id, "--cpus", CPUS]
   vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.define "#{HOST_NAME}" do |c|
    c.vm.box = "#{BOX}"
    c.vm.hostname = "#{HOST_NAME}"
    c.vm.network :private_network,  ip: PRIVATE_IP
  end

end
